root_load_save_dir: /work3/s253892/T-GRAB/scratch
data_loc: /work3/s253892/T-GRAB/scratch/data

lag: 4
num_patterns: 4000
num_nodes: 100
val_ratio: 0.1
test_ratio: 0.1
test_inductive_ratio: 0.0
test_inductive_num_nodes_ratio: 0.0
er_prob: 0.002
er_prob_inductive: 0.0
seed: 3457
wandb_project: T-GRAB_ce_final

data: (${.lag}, ${.num_patterns})/cause_effect-${.num_nodes}n-${.val_ratio}vr-${.test_ratio}tr-${.test_inductive_ratio}tir-${.test_inductive_num_nodes_ratio}tinnr-${.er_prob}ep-${.er_prob_inductive}epi
node_feat: ONE_HOT
node_feat_dim: 1
