root_load_save_dir: /Users/valentinacristoferi/THESIS/T-GRAB/scratch
data_loc: /Users/valentinacristoferi/THESIS/T-GRAB/scratch/data

lag: 8
branch_len: 4
num_snapshots: 4000
num_nodes: 100
num_branches: 6
val_ratio: 0.1
test_ratio: 0.1
seed: 1235
wandb_project: T-GRAB_lr_final

data: (${.lag}, ${.branch_len})/long_range-${.num_snapshots}ns-${.num_nodes}nn-${.num_branches}nb-${.val_ratio}vr-${.test_ratio}tr
node_feat: ONE_HOT
node_feat_dim: 1
