data: (64, 4000)/cause_effect-100n-0.1vr-0.1tr-0.0tir-0.0tinnr-0.002ep-0.0epi
data_loc: /Users/valentinacristoferi/THESIS/T-GRAB/scratch/data
root_load_save_dir: /Users/valentinacristoferi/THESIS/T-GRAB/scratch
node_feat: ONE_HOT
node_feat_dim: 1
seed: 3457
wandb_project: T-GRAB_ce_final
